#!/bin/bash
$passwd="paswd"
un="andrew"
db="test_app_db"

while read -r output;
do
    echo $output | awk '{print $0}'
    #do something
done< <(mysql -u $un -p$passwd $db -h 0 -e "select * from test_users;" |column -t)
